spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: detect

---

spring:
 profiles: dev
 h2:
   console:
     path: /h2
     enabled: true
 datasource:
   url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;
   username: sa
   password:
   platform: h2
   driver-class-name: org.h2.Driver
 jpa:
   hibernate:
     ddl-auto: create
   show-sql: true
   database-platform: org.hibernate.dialect.H2Dialect
   properties:
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false