
-- INSERT INTO SKILL (SKILL_ID, NAME, ACTIVE) VALUES (1, 'JAVA', TRUE);

-- INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, SKILL_TYPE_DESC, IS_ACTIVE, IS_CORE) VALUES (1,'Spring Data', 'Magic', TRUE, TRUE);
-- INSERT INTO SKILL_TYPE (SKILL_TYPE_ID, SKILL_TYPE_NAME, SKILL_TYPE_DESC, IS_ACTIVE, IS_CORE) VALUES (2,'Spring Boot', 'More magic', TRUE, TRUE);
--
-- INSERT INTO SKILL_SKILLTYPE (SKILL_ID, SKILL_TYPE_ID) VALUES (1, 1);
-- INSERT INTO SKILL_SKILLTYPE (SKILL_ID, SKILL_TYPE_ID) VALUES (1, 2);


INSERT INTO SKILL (NAME, ACTIVE) VALUES ('JAVA', TRUE);
INSERT INTO SKILL (NAME, ACTIVE) VALUES (\'JAVA', TRUE);


